version: '3.9'

services:

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: production
    restart: always
    environment:
      - PORT=8080
      - DB_URL=mongodb://root:pass@mongodb:27017
      - SECRET_KEY="xmltim4tajnikljuc"
    container_name: "airplane_server"
    hostname: "airplane_server"
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:6.0
    restart: always
    container_name: airplane_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: airplaneMongoDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  web:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: production
    environment:
      - URL="http://server:8080"
      - NGINX_PORT=80
    ports:
      - "127.0.0.1:3000:3000"
    links: 
      - server

volumes:
  mongo_store: