version: '3.9'
services:
  mongodb:
    image: mongo:6.0
    container_name: airplane_mongodb
    ports:
      - '27017:27017'
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: production
    environment:
      - PORT=8080
      - DB_URL="mongodb://mongodb:27017"
      - SECRET_KEY="xmltim4tajnikljuc"
    container_name: airplane_api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
  web:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: production
    environment:
      - URL="http://api:8080"
      - NGINX_PORT=80
    ports:
      - 3000:3000
    links: 
      - api